project:
  type: website

website:
  title: "6YS Blog"
  site-url: https://6yardscreamers.netlify.app
  favicon: "images/soccer2.png"
  open-graph: true
  twitter-card:
    image: images/soccer2.png
    creator: "@6yardscreamers"
  page-footer: 
    center: |
      [Contact Christina](mailto:6ysblog@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org)
    background: "black"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd 
    right:
      - about.qmd
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/christina6YS.bsky.social
      - icon: twitter
        href: https://twitter.com/6yardscreamers
      - icon: mastodon
        href: https://mastodon.skrimmage.com/@Christina
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: styles.css
    code-link: true

editor: visual

comments: 
  giscus: 
    repo: Chris6YS/quarto-website-6ys
    

